name: Package and test on windows
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  build_test_windows:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '***SKIPBUILD***')"
    env:
        TEST_LEVEL: 1
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ '3.9' ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Config github user
        run: |
          git config --global user.email "idm_bamboo_user@idmod.org"
          git config --global user.name "BambooUser-IDM"
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Build and install package
        uses: ./.github/actions/build-install-package
        with:
          pyproject_file: 'pyproject.toml'
      - name: run unit tests
        run: |
          pip install -r requirements.txt
          python -m unittest discover .
        working-directory: ./tests
