name: Package, test, and publish
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'emod_api/**'
      - 'pyproject.toml'
  permissions:
    contents: write # Allow writing to the repository (e.g., commits, pushes)
jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '***SKIPBUILD***')"
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ '3.9' ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Config github user
        run: |
          git config --global user.email "idm_bamboo_user@idmod.org"
          git config --global user.name "BambooUser-IDM"
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: install snappy
        run: sudo apt-get install libsnappy-dev
        shell: bash
      - id: build-install
        name: Build and install package
        uses: ./.github/actions/build-install-package
        with:
          pyproject_file: 'pyproject.toml'
      - name: run unit tests
        run: |
          pip install -r requirements.txt
          python -m unittest discover .
        working-directory: ./tests
      - name: Push version bump
        if: success()
        run: git push
      - name: twine upload
        if: success()
        run: twine upload --verbose --repository-url https://packages.idmod.org/api/pypi/idm-pypi-staging/ --username ${{ secrets.STAGING_ARTIFACTORY_USERNAME }} --password ${{ secrets.STAGING_ARTIFACTORY_PASSWORD }} dist/*
        working-directory: ./
