# This workflow will Rebuild emod-api Docs triggered when changes to rst, python or requirements.txt files are intended.

name: Rebuild emod-api docs
on:
  push:
    paths: 
      - '**.py'
      - '**/*docs/**'
  pull_request:
    paths:
      - '**.py'
      - '**/*docs/**'

jobs:
  emod-api-docs-rebuild:

    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}

    # Environment Setup
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
          python-version: 3.9

    # emod-api package setup 
    - name: Install emod-api package
      run: |
        python -m pip install --upgrade pip
        pip install -e . --extra-index-url=https://packages.idmod.org/api/pypi/pypi-production/simple

    # docs 
    - name: Install documentation build requirements
      run: |
        pip install -r docs/requirements.txt --extra-index-url=https://packages.idmod.org/api/pypi/pypi-production/simple

    - name: Build docs - html - no break
      working-directory: 'docs'
      run: |
        make clean
        make htmlnobreak

