name: Test and deploy to staging

permissions:
  contents: write # Allow writing to the repository (e.g., commits, pushes)

on:
  push:
    branches:
      - main
    paths:
      - 'emod_api/**'
      - 'pyproject.toml'

jobs:
  run-tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml

  staging-build-package:
    name: Push to staging
    needs: [run-tests]
    uses: ./.github/workflows/staging-build-package.yml
    secrets:
      STAGING_ARTIFACTORY_USERNAME: ${{ secrets.STAGING_ARTIFACTORY_USERNAME }}
      STAGING_ARTIFACTORY_PASSWORD: ${{ secrets.STAGING_ARTIFACTORY_PASSWORD }}
